### ISSUE TITLE
Use a smarter format for JSON binary serialization

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#1382]
Please see [issue 2437](https://github.com/vibe-d/vibe.d/issues/2437)

**Comment by AndrejMitrovic** [comment]
@ferencdg can you close this if it's resolved now? Thanks.

**Comment by Geod24** [comment]
It's not yet resolved: https://github.com/vibe-d/vibe.d/pull/2505

**Comment by Geod24** [comment]
Upstream PR has been merged, ~@ferencdg could you apply the necessary diff to Agora ?~
Actually nvm I'll do it, since the diff is minimal, but the verification isn't.
